version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: 0shift/reverseproxy 
  backend_user:
    build:
      context: ../../uda-api-user
    image: 0shift/uda-api-user
  backend_feed:
    build:
      context: ../../uda-api-feed  
    image: 0shift/uda-api-feed
  frontend:
    build:
      context: ../../uda-frontend  
    image: 0shift/uda-frontend:local
